language: node_js
install:
- yarn
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn report-coverage
- yarn build
deploy:
  provider: npm
  email: gmoura.nas@gmail.com
  api_key:
    secure: fXCb0qZmC2X0MTKIa/FH3UpgsziI9SkubThLu089BUHQ2ypWO15aGYCelu8+TJDNES1gA74s+LfQtduL0SkAoE68XJ8bzHCTfaDLkHVBDKqANfraKRnMzbgBnYGcGyvOs06KRxqgwDKXNpGmCdihki9ZSJXS4OkQUJLDlpVVYvCjWnOiRK+RkSoA2569rHLeF/uqYTgQJZ0WmTOcUNY20m0CW5zAStaEIPHUTnj6xETvDz62ZS93uQYuS5MI0pOCR2nHbI30OKPyFbQwRol/S2yp2B26vGBufl+ojHou/hGofkY9J6zCPXwTABIge2mRx176pe6TetIgeIAQq5qzz4ACXO8HrvU1Ajd7+4H+fnt9x/x4aOLpWeOax+MgWknkMAzTg41kSi5MKwMAhS3kKKrNRyA1NqpgdExrX1J/Dz+Ll3IOCTyz5l8pabstcchxUkyT8wEggXrg9WE3KtVRLj2LOSL8Sbvin1V47Z+a7KpLCHajB0waZGhSvBm1+U1rkjOAN7Keeb6ffnAr8PTCUbEplQDjxOPubwfqGM21RTnfRUXawuodJxhkdj6YeHTSuKI1+jrsOB0XK3iL6hIixX7cCiXmeN7jzRP9ZYvU81gb0xGR8et6XjlCWvb30jDZlgI8xMQP20NMs994x0XQsJtBIKR/jhEZ9O07Dvcnmxg=
  on:
    tags: next
    repo: gmoura/react-pinco
