language: node_js
install:
  - yarn
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn report-coverage
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  domain: $github_token
  project: ./build/
on:
  branch: master