language: node_js
install:
- yarn
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn report-coverage
- yarn build
deploy:
  provider: npm
  email: gmoura.nas@gmail.com
  api_key:
    secure: CZ3ncnR73q0dr5VXut4KRKsn1VSZ8jsG7i2hrgxyK0XZ11+qbovLa80G5hoWHHbqD8T2oQWGk/lhxan017XBFa/S85Kmmzy0t1EzguciEnxumh24CGxwa5+4HuuSzbaL/6QyxKjddAxFb540ZLdUKQsUrWLa7k0jQbmKbma0TcP6IksR/zGUCZKJE1cLlyQeDXqx4c7fWEbzUZds25FLAN42iFknRz3V9Ye0D8KBlEtrJAnMF2ZzZXARElImlLQynRWLj1cFueAUihfVLGz3f6RAKPWbUcH9AwwfEVpj45tIfqW5ArW2H0cflzP6HYJxvxorr9n540AspqFziLWeE6t5x7IPBUjIm20braV1+Ud3Heleziv2afeex+GyT2SHwaAou1tKnGBrtcbH+c/EU/RAcusvtd0HjFSKkMxxr/RHWkjhYvb4XsJIXG70yU3MH6YGEFx7U4IbCjHA/9dYHrUjMXFYTXsqp9JYjbnZie+49g0X3kBY8/GCYDSB0MN/BYSjZETQshxNH4MucOmWUZh7VKw45/Nhbt1xxzsxRlFG9w7IYQCSDLOx7Ws9lT3Qu+sA+W8inxBemtWP0d+pKNl12QDqU+VZN6cX1nEM/oNjhUdnh9Y6Fe7sNNCvx9UpvCm+/mNuQN3NpAU1Ww7o2d32I5kXZtVPS4Eq9VErhkM=
  on:
    tags: next
    repo: gmoura/react-pinco
